### ISSUE TITLE
Legacy Camera on thirteen

### ISSUE THREAD

**Issue by damolmo** [Galaxy-J5-Unofficial-LineageOS-Sources/samsung_msm8916_common#4]
aosp tag : android-13.0.0_r4
Builds : Yes
Boots : No, mm-qcamera-daemon crash

Current Status: Disabled
ref :
https://github.com/Galaxy-J5-Unofficial-LineageOS-Sources/samsung_msm8916_common/blob/cfa83a93ac870b9d00194ec67afc4a229ee297e0/lineage_msm8916.mk#L123-L133

**Comment by Luminous418** [comment]
@daviiid99 Nooooo :'c
